//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by InstantMessaging.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_INSTANTMESSAGING_DIALOG     102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_BG                   130
#define IDB_CHATROOM_DISABLE            186
#define IDB_CHATROOM_DOWN               187
#define IDB_CHATROOM_HOVER              188
#define IDB_CHATROOM_NORMAL             189
#define IDB_ADDFRIEND_DISABLE           190
#define IDB_ADDFRIEND_DOWN              191
#define IDB_ADDFRIEND_HOVER             192
#define IDB_ADDFRIEND_NORMAL            193
#define IDB_SHARESCREEN_NORMAL          194
#define IDB_SENDFILES_DISABLE           195
#define IDB_SENDFILES_DOWN              196
#define IDB_SENDFILES_HOVER             197
#define IDB_SENDFILES_NORMAL            198
#define IDB_SHARESCREEN_DISABLE         199
#define IDB_SHARESCREEN_DOWN            200
#define IDB_SHARESCREEN_HOVER           201
#define IDB_WHITEBOARD_DISABLE          202
#define IDB_WHITEBOARD_DOWN             203
#define IDB_WHITEBOARD_HOVER            204
#define IDB_WHITEBOARD_NORMAL           205
#define IDB_BITMAP1                     206
#define IDB_BITMAP2                     207
#define IDB_BITMAP3                     208
#define IDB_BITMAP4                     209
#define IDB_BITMAP5                     210
#define IDB_BITMAP6                     211
#define IDB_BITMAP7                     212
#define IDB_BITMAP8                     213
#define IDB_BITMAP9                     214
#define IDB_BITMAP10                    215
#define IDB_BITMAP11                    216
#define IDB_BITMAP12                    217
#define IDB_BITMAP13                    218
#define IDB_BITMAP14                    219
#define IDB_BITMAP15                    220
#define IDB_BITMAP16                    221
#define IDB_BITMAP17                    222
#define IDB_BITMAP18                    223
#define IDB_BITMAP19                    224
#define IDB_BITMAP20                    225
#define IDB_BITMAP21                    226
#define IDB_BITMAP22                    227
#define IDB_BITMAP23                    228
#define IDB_BITMAP24                    229
#define IDB_BITMAP25                    230
#define IDB_BITMAP26                    231
#define IDB_BITMAP27                    232
#define IDB_BITMAP28                    233
#define IDB_BITMAP29                    234
#define IDB_BITMAP30                    235
#define IDB_BITMAP31                    236
#define IDB_BITMAP32                    237
#define IDB_BITMAP33                    238
#define IDB_BITMAP34                    239
#define IDB_BITMAP35                    240
#define IDB_BITMAP36                    241
#define IDB_BITMAP37                    242
#define IDB_BITMAP38                    243
#define IDB_BITMAP39                    244
#define IDB_BITMAP40                    245
#define IDB_BITMAP41                    246
#define IDB_BITMAP42                    247
#define IDB_BITMAP43                    248
#define IDB_BITMAP44                    249
#define IDB_BITMAP45                    250
#define IDB_BITMAP46                    251
#define IDB_BITMAP47                    252
#define IDB_BITMAP48                    253
#define IDB_BITMAP49                    254
#define IDB_BITMAP50                    255
#define IDB_BITMAP51                    256
#define IDB_BITMAP52                    257
#define IDB_BITMAP53                    258
#define IDB_BITMAP54                    259
#define IDB_BITMAP55                    260
#define IDB_BITMAP56                    261
#define IDB_BITMAP57                    262
#define IDB_BITMAP58                    263
#define IDB_BITMAP59                    264
#define IDB_BITMAP60                    265
#define IDB_BITMAP61                    266
#define IDB_BITMAP62                    267
#define IDB_BITMAP63                    268
#define IDB_BITMAP64                    269
#define IDB_BITMAP65                    270
#define IDB_BITMAP66                    271
#define IDB_BITMAP67                    272
#define IDB_BITMAP68                    273
#define IDB_BITMAP69                    274
#define IDB_BITMAP70                    275
#define IDB_BITMAP71                    276
#define IDB_BITMAP72                    277
#define IDB_BITMAP73                    278
#define IDB_BITMAP74                    279
#define IDB_BITMAP75                    280
#define IDB_BITMAP76                    281
#define IDB_BITMAP77                    282
#define IDB_BITMAP78                    283
#define IDB_BITMAP79                    284
#define IDB_BITMAP80                    285
#define IDB_BITMAP81                    286
#define IDB_BITMAP82                    287
#define IDB_BITMAP83                    288
#define IDR_MENU1                       290
#define IDD_SETTING                     291
#define IDI_OFFLINE                     292
#define IDB_CAMERA                      293
#define IDB_DELETE                      295
#define IDR_MENU2                       296
#define IDD_CHATROOM_SERVER             297
#define IDB_CHATROOM_ADD_DISABLE        299
#define IDB_CHATROOM_ADD_DOWN           300
#define IDB_CHATROOM_ADD_HOVER          301
#define IDB_CHATROOM_ADD_NORMAL         302
#define IDB_CHATROOM_DEL_DISABLE        303
#define IDB_CHATROOM_DEL_DOWN           304
#define IDB_CHATROOM_DEL_HOVER          305
#define IDB_CHATROOM_DEL_NORMAL         306
#define IDD_CHATROOM_CLIENT             309
#define IDD_CHAT                        310
#define IDD_SHARESCREEN_CLIENT          313
#define IDD_SENDFILES_SERVER            314
#define IDD_SENDFILES_CLIENT            315
#define IDD_SENDFILES_USER              316
#define IDD_SHARESCREEN_SERVER          317
#define IDD_WHITEBOARD_SERVER           318
#define IDB_WHITEBOARD_ERASE_NORMAL     319
#define IDB_WHITEBOARD_ERASE_DISABLE    320
#define IDB_WHITEBOARD_ERASE_DOWN       321
#define IDB_WHITEBOARD_ERASE_HOVER      322
#define IDB_WHITEBOARD_ELLIPSE_NORMAL   335
#define IDB_WHITEBOARD_ELLIPSE_DISABLE  336
#define IDB_WHITEBOARD_ELLIPSE_DOWN     337
#define IDB_WHITEBOARD_ELLIPSE_EMPTY_DISABLE 338
#define IDB_WHITEBOARD_ELLIPSE_EMPTY_DOWN 339
#define IDB_WHITEBOARD_ELLIPSE_EMPTY_HOVER 340
#define IDB_WHITEBOARD_ELLIPSE_EMPTY_NORMAL 341
#define IDB_WHITEBOARD_ELLIPSE_HOVER    342
#define IDB_WHITEBOARD_PENCIL_NORMAL    343
#define IDB_WHITEBOARD_LINE_DISABLE     344
#define IDB_WHITEBOARD_LINE_DOWN        345
#define IDB_WHITEBOARD_LINE_HOVER       346
#define IDB_WHITEBOARD_LINE_NORMAL      347
#define IDB_WHITEBOARD_PENCIL_DISABLE   348
#define IDB_WHITEBOARD_PENCIL_DOWN      349
#define IDB_WHITEBOARD_PENCIL_HOVER     350
#define IDB_WHITEBOARD_RECTANGLE_NORMAL 351
#define IDB_WHITEBOARD_RECTANGLE_DISABLE 352
#define IDB_WHITEBOARD_RECTANGLE_DOWN   353
#define IDB_WHITEBOARD_RECTANGLE_EMPTY_DISABLE 354
#define IDB_WHITEBOARD_RECTANGLE_EMPTY_DOWN 355
#define IDB_WHITEBOARD_RECTANGLE_EMPTY_HOVER 356
#define IDB_WHITEBOARD_RECTANGLE_EMPTY_NORMAL 357
#define IDB_WHITEBOARD_RECTANGLE_HOVER  358
#define IDB_WHITEBOARD_WIDTH_2_NORMAL   359
#define IDB_WHITEBOARD_WIDTH_1_DISABLE  360
#define IDB_WHITEBOARD_WIDTH_1_DOWN     361
#define IDB_WHITEBOARD_WIDTH_1_HOVER    362
#define IDB_WHITEBOARD_WIDTH_1_NORMAL   363
#define IDB_WHITEBOARD_WIDTH_2_DISABLE  364
#define IDB_WHITEBOARD_WIDTH_2_DOWN     365
#define IDB_WHITEBOARD_WIDTH_2_HOVER    366
#define IDB_WHITEBOARD_WIDTH_4_NORMAL   367
#define IDB_WHITEBOARD_WIDTH_3_DISABLE  368
#define IDB_WHITEBOARD_WIDTH_3_DOWN     369
#define IDB_WHITEBOARD_WIDTH_3_HOVER    370
#define IDB_WHITEBOARD_WIDTH_3_NORMAL   371
#define IDB_WHITEBOARD_WIDTH_4_DISABLE  372
#define IDB_WHITEBOARD_WIDTH_4_DOWN     373
#define IDB_WHITEBOARD_WIDTH_4_HOVER    374
#define IDC_ERASER_1                    376
#define IDC_ERASER_2                    377
#define IDC_ERASER_3                    378
#define IDC_ERASER_4                    379
#define IDC_PENCIL                      380
#define IDC_CURSOR                      381
#define IDD_WHITEBOARD_CLIENT           382
#define IDD_VIDEOCHAT                   383
#define IDI_MIKE                        384
#define IDI_TRUMP                       385
#define IDB_BITMAP84                    387
#define IDB_BITMAP85                    388
#define IDC_LIST5                       1006
#define IDC_LIST_FRIENDS                1006
#define IDC_COMBO_FRIEND                1008
#define IDC_BTN_ADDFRIEND               1009
#define IDC_BTN_CHATROOM                1010
#define IDC_BTN_SHARESCREEN             1011
#define IDC_BTN_WHITEBOARD              1012
#define IDC_BTN_SENDFILES               1013
#define IDC_COMBO_STATE                 1014
#define IDC_STATIC_FACE                 1016
#define IDC_EDIT_NICKNAME               1019
#define IDC_HOTKEY                      1021
#define IDC_COMBO_FACE                  1024
#define IDB_SAVE                        1028
#define IDB_CANCEL                      1029
#define IDC_COMBOBOXEX_FACE             1030
#define IDC_COMBO_IP                    1033
#define IDB_CLOSE                       1038
#define IDC_LIST_INCHAT                 1041
#define IDC_LIST_OUTOFCHAT              1042
#define IDB_ADDFRIENDS                  1043
#define IDB_DELFRIENDS                  1044
#define IDE_RECEIVED                    1045
#define IDE_SEND                        1046
#define IDB_COLSE                       1047
#define IDB_SEND                        1048
#define IDC_RICHTEXT_RECEIVED           1051
#define IDC_RICHTEXT_SEND               1052
#define IDS_NICKNAME                    1053
#define IDS_IP                          1054
#define IDC_SAVEFILE                    1057
#define IDB_LOADFILE                    1058
#define IDS_FACE                        1059
#define IDS_SCREEN                      1062
#define IDC_LIST_SEND                   1063
#define IDC_LIST_RECEIVE                1065
#define IDB_ADD                         1068
#define IDC_LIST_USER                   1068
#define IDC_CHECK_AUTOADDFRIENDS        1069
#define IDB_ADD_SECTION                 1072
#define IDC_LIST_INSHARESCREEN          1073
#define IDC_LIST_OUTOFSHARESCREEN       1074
#define IDE_INFORMATION                 1075
#define IDB_ERASER                      1078
#define IDB_PENCIL                      1079
#define IDB_LINE                        1080
#define IDB_RECTANGLE_EMPTY             1081
#define IDB_RECTANGLE                   1082
#define IDB_ELLIPSE_EMPTY               1083
#define IDB_ELLIPSE                     1084
#define IDB_WIDTH_2                     1085
#define IDS_COLOR                       1086
#define IDC_LIST_INWHITEBOARD           1087
#define IDC_LIST_OUTOFWHITEBOARD        1088
#define IDS_CANVAS                      1089
#define IDB_WIDTH_1                     1090
#define IDB_WIDTH_3                     1091
#define IDB_WIDTH_4                     1092
#define IDC_TRUMP                       1095
#define IDC_MIKE                        1096
#define IDC_SLIDER_TRUMP                1097
#define IDC_SLIDER_MIKE                 1098
#define IDS_FRIEND                      1099
#define IDS_SELF                        1100
#define IDS_TRUMP                       1101
#define IDS_MIKE                        1102
#define IDB_SELF                        1103
#define IDB_SETTING                     1104
#define IDC_IPADDRESS1                  1106
#define IDC_COMBO1                      1110
#define IDM_SETTING                     32785
#define IDM_EXIT                        32786
#define IDM_STATE                       32787
#define IDM_SENDMESSAGE                 32788
#define IDM_VIDEOCHAT                   32789
#define IDM_DELETEUSER                  32790
#define IDM_CHATROOM                    32791
#define IDM_SENDFILES                   32792
#define IDM_RECEIVEFILES                32793
#define IDM_SHARESCREEN                 32794
#define IDM_WHITEBOARD                  32795
#define IDD_CAPTUREVIDEO                35000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        398
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1111
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
